packages:
  - packages/*

catalog:
  '@babel/core': 7.28.4
  '@babel/types': 7.28.5
  '@biomejs/biome': 2.2.4
  '@dotenvx/dotenvx': 1.51.1
  '@socketsecurity/lib': 5.0.1
  '@types/node': 24.9.2
  acorn: 8.14.0
  acorn-walk: 8.3.4
  adm-zip: 0.5.16
  del-cli: 6.0.0
  esbuild: 0.25.11
  magic-string: 0.30.19
  postject: 1.0.0-alpha.6
  tar: 7.4.3
  vitest: 4.0.3
  yoctocolors-cjs: 2.1.3
