packages:
  - packages/*

catalog:
  '@babel/core': 7.28.4
  '@babel/parser': 7.28.4
  '@babel/traverse': 7.28.4
  '@babel/types': 7.28.5
  '@biomejs/biome': 2.3.6
  '@socketsecurity/lib': 4.2.0
  '@types/node': 24.9.2
  del-cli: 6.0.0
  esbuild: 0.25.11
  magic-string: 0.30.19
  postject: 1.0.0-alpha.6
  vitest: 4.0.3
  yoctocolors-cjs: 2.1.3
