packages:
  - packages/*

catalog:
  '@babel/core': 7.29.0
  '@babel/types': 7.28.5
  '@biomejs/biome': 2.2.4
  '@dotenvx/dotenvx': 1.31.0
  '@socketsecurity/lib': 5.7.0
  '@types/node': 24.9.2
  '@vitest/coverage-v8': 4.0.3
  acorn: 8.14.0
  acorn-walk: 8.3.4
  adm-zip: 0.5.16
  del-cli: 6.0.0
  esbuild: 0.25.11
  magic-string: 0.30.19
  octokit: 5.0.5
  postject: 1.0.0-alpha.6
  tar: 7.4.3
  vitest: 4.0.3
  yoctocolors-cjs: 2.1.3
