#!/bin/bash
# DO NOT EDIT — generated by scripts/emit-docker-build.mts from
# scripts/build-step-defs.mts. Regenerate via:
#
#   pnpm --filter boringssl-builder run emit-docker-build
#
# Runs inside the manylinux2014 container — no Node, no pnpm.
# Inputs (env vars expected to be set by the Dockerfile):
#   UPSTREAM_DIR       — path to upstream/boringssl/ inside the container
#   CMAKE_BUILD_DIR    — scratch dir for cmake's intermediate output
#   OUT_LIB_DIR        — destination for libsmol_*.a artifacts
#   OUT_INCLUDE_DIR    — destination for the prefixed openssl/*.h tree

set -euo pipefail

: "${UPSTREAM_DIR:?UPSTREAM_DIR not set}"
: "${CMAKE_BUILD_DIR:?CMAKE_BUILD_DIR not set}"
: "${OUT_LIB_DIR:?OUT_LIB_DIR not set}"
: "${OUT_INCLUDE_DIR:?OUT_INCLUDE_DIR not set}"

mkdir -p "$CMAKE_BUILD_DIR" "$OUT_LIB_DIR" "$OUT_INCLUDE_DIR"


# cmake configure
echo "→ cmake configure"
cmake -S $UPSTREAM_DIR -B $CMAKE_BUILD_DIR -DCMAKE_BUILD_TYPE=Release -DBORINGSSL_PREFIX=smol -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_TESTING=OFF

# cmake build crypto + ssl
echo "→ cmake build crypto + ssl"
cmake --build $CMAKE_BUILD_DIR --config Release --parallel --target crypto --target ssl

# Publish renamed static libs
if [ ! -f "$CMAKE_BUILD_DIR/libcrypto.a" ]; then
  echo "× expected build artifact not found: $CMAKE_BUILD_DIR/libcrypto.a" >&2
  exit 1
fi
cp "$CMAKE_BUILD_DIR/libcrypto.a" "$OUT_LIB_DIR/libsmol_crypto.a"
echo "  $(basename '$CMAKE_BUILD_DIR/libcrypto.a') → $(basename '$OUT_LIB_DIR/libsmol_crypto.a')"
if [ ! -f "$CMAKE_BUILD_DIR/libssl.a" ]; then
  echo "× expected build artifact not found: $CMAKE_BUILD_DIR/libssl.a" >&2
  exit 1
fi
cp "$CMAKE_BUILD_DIR/libssl.a" "$OUT_LIB_DIR/libsmol_ssl.a"
echo "  $(basename '$CMAKE_BUILD_DIR/libssl.a') → $(basename '$OUT_LIB_DIR/libsmol_ssl.a')"

# Publish include/ tree
cp -R "$UPSTREAM_DIR/include/." "$OUT_INCLUDE_DIR/"
echo "  include/ → $OUT_INCLUDE_DIR"

echo "✓ boringssl-builder docker build complete"
