import type {
  AdapterKind,
  CurrentDisposition,
  MigrationManifestRow,
  NodeSmolExtractionTarget,
  PlannedDestination,
  RemovalStatus,
} from './node-smol-migration-manifest.mts'

function row(
  currentPath: string,
  publicPackage: string,
  currentDisposition: CurrentDisposition,
  plannedDestination: PlannedDestination,
  adapterKind: AdapterKind,
  lockstepTracker: string | undefined,
  removalStatus: RemovalStatus = 'retained',
  upstreamPin: string | undefined = undefined,
): MigrationManifestRow {
  return {
    adapterKind,
    currentDisposition,
    currentPath,
    lockstepTracker,
    plannedDestination,
    publicPackage,
    removalStatus,
    upstreamPin,
  }
}

function aiNodeRows(): MigrationManifestRow[] {
  const platformRows = [
    'darwin-arm64',
    'darwin-x64',
    'linux-arm64-gnu',
    'linux-arm64-musl',
    'linux-x64-gnu',
    'linux-x64-musl',
    'win32-arm64-msvc',
    'win32-x64-msvc',
  ] as const
  return platformRows.map(platform =>
    row(
      `packages/npm/@node-smol/ai.node-${platform}`,
      `@node-smol/ai.node-${platform}`,
      'node-smol-core',
      'node-smol',
      'release-pack',
      undefined,
    ),
  )
}

export const NODE_SMOL_MIGRATION_MANIFEST: readonly MigrationManifestRow[] = [
  row(
    'packages/ai-infra',
    'ai-infra',
    'node-smol-core',
    'node-smol',
    'napi',
    undefined,
  ),
  row(
    'packages/bin-infra',
    'bin-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/bin-stub-builder',
    'bin-stub-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/binflate',
    'binflate',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/binject',
    'binject',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/binpress',
    'binpress',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/boringssl-builder',
    'boringssl-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/build-infra',
    'build-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/codesign-infra',
    'codesign-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/codet5-models-builder',
    'codet5-models-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/curl-builder',
    'curl-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/dawn-builder',
    'dawn-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/glibc-shims-infra',
    'glibc-shims-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/keychain-addon-builder',
    'keychain-addon-builder',
    'destination-owned-build-tool',
    'sockeye',
    'napi',
    'packages/keystore-infra/README.md',
    'pending-move',
  ),
  row(
    'packages/keychain-cli-builder',
    'keychain-cli-builder',
    'destination-owned-build-tool',
    'sockeye',
    'cli',
    'packages/keystore-infra/README.md',
    'pending-move',
  ),
  row(
    'packages/keystore-infra',
    'keystore-infra',
    'destination-owned-rust-crate',
    'sockeye',
    'none',
    'packages/keystore-infra/README.md',
    'pending-move',
  ),
  row(
    'packages/libpq-builder',
    'libpq-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/lief-builder',
    'lief-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/lsquic-infra',
    'lsquic-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/minilm-builder',
    'minilm-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/models',
    'models',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/napi-go-infra',
    'napi-go-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/node-smol-builder',
    'node-smol-builder',
    'node-smol-core',
    'node-smol',
    'build-tool',
    'packages/node-smol-builder/README.md',
    'pending-move',
  ),
  row(
    'packages/npm/@node-smol/ai',
    '@node-smol/ai',
    'node-smol-core',
    'node-smol',
    'napi',
    'packages/node-smol-builder/README.md',
    'pending-move',
  ),
  ...aiNodeRows(),
  row(
    'packages/onnxruntime-builder',
    'onnxruntime-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/opentui-builder',
    'opentui-builder',
    'retired-duplicate',
    'node-smol',
    'builtin',
    'packages/tui-infra/README.md',
    'pending-retire',
  ),
  row(
    'packages/proteus-builder',
    'proteus-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/smol-ai-builder',
    'smol-ai-builder',
    'node-smol-core',
    'node-smol',
    'napi',
    'packages/ai-infra/package.json',
    'pending-move',
  ),
  row(
    'packages/temporal-infra',
    'temporal-infra',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
  row(
    'packages/tui-infra',
    'tui-infra',
    'destination-owned-rust-crate',
    'stuie',
    'builtin',
    'packages/tui-infra/README.md',
    'pending-move',
  ),
  row(
    'packages/yoga-layout-builder',
    'yoga-layout-builder',
    'node-smol-core',
    'socket-btm',
    'build-tool',
    undefined,
  ),
]

export const NODE_SMOL_NEXT_EXTRACTION_TARGETS: readonly NodeSmolExtractionTarget[] =
  [
    {
      name: 'ultraviolet',
      note: 'TUI library not yet integrated into node-smol; publish independently first.',
      plannedDestination: 'node-smol',
      sourcePlan: '.claude/plans/repo/builder-orchestration.md',
      tier: 'tier-1b',
    },
    {
      name: 'codet5-models',
      note: 'ONNX model leaf published for standalone consumers (socket-cli etc.).',
      plannedDestination: 'node-smol',
      sourcePlan: '.claude/plans/repo/builder-orchestration.md',
      tier: 'tier-1b',
    },
    {
      name: 'minilm',
      note: 'ONNX model leaf published for standalone consumers (socket-cli etc.).',
      plannedDestination: 'node-smol',
      sourcePlan: '.claude/plans/repo/builder-orchestration.md',
      tier: 'tier-1b',
    },
  ]
