/**
 * @fileoverview Tests for SEA (Single Executable Application) support with automatic Brotli compression.
 *
 * Tests different blob formats:
 * - Plain JavaScript (.js)
 * - Pre-compressed Brotli (.js.br)
 * - Compression flags (useCompression: true/false)
 *
 * Note: These tests require a built smol binary at build/{dev,prod}/out/Final/node.
 * Run `pnpm build --dev` first to create the binary.
 */

import { existsSync, promises as fs } from 'node:fs'
import { MACHO_SEGMENT_NODE_SEA } from '../../../bin-infra/test-helpers/segment-names.mjs'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { describe, expect, it, beforeAll, afterAll } from 'vitest'

import { safeDelete } from '@socketsecurity/lib/fs'
import { spawn } from '@socketsecurity/lib/spawn'

import { runBinject } from '../helpers/binject.mjs'
import { getLatestFinalBinary } from '../paths.mjs'

// Get the latest Final binary from build/{dev,prod}/out/Final/node
// This is the production binary suitable for injection and execution
const finalBinaryPath = getLatestFinalBinary()

// Skip all tests if no final binary is available
const skipTests = !finalBinaryPath || !existsSync(finalBinaryPath)

// Use system temp directory for test artifacts.
const testTmpDir = path.join(tmpdir(), 'socket-btm-sea-tests')

describe.skipIf(skipTests)(
  'SEA (Single Executable Application) support',
  () => {
    beforeAll(async () => {
      // Create test tmp directory.
      await fs.mkdir(testTmpDir, { recursive: true })
    })

    afterAll(async () => {
      // Clean up test tmp directory.
      await safeDelete(testTmpDir)
    })

    describe('hello-world with plain JavaScript blob', () => {
      const testDir = path.join(testTmpDir, 'hello-plain-js')
      let seaBinary

      beforeAll(async () => {
        await fs.mkdir(testDir, { recursive: true })

        // Create hello-world JavaScript.
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `console.log('Hello from SEA!');\nconsole.log('Compression: automatic');\n`,
        )

        // Create SEA config with compression enabled (default).
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify(
            {
              main: 'app.js',
              output: 'app.blob',
              disableExperimentalSEAWarning: true,
              useCodeCache: true,
            },
            null,
            2,
          ),
        )

        // SEA blob will be generated by binject from sea-config.json

        // Copy smol binary for injection.
        seaBinary = path.join(testDir, 'hello-plain-js')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await fs.chmod(seaBinary, 0o755)

        // Inject SEA blob using postject.
        const injectResult = await runBinject(
          seaBinary,
          'NODE_SEA_BLOB',
          'sea-config.json',
          {
            testDir,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
          },
        )

        expect(injectResult.code).toBe(0)
      })

      it('should execute and output hello-world message', async () => {
        const result = await spawn(seaBinary, [], {
          cwd: testDir,
        })

        expect(result.code).toBe(0)
        expect(result.stdout).toContain('Hello from SEA!')
        expect(result.stdout).toContain('Compression: automatic')
      })
    })

    describe('hello-world with compression disabled', () => {
      const testDir = path.join(testTmpDir, 'hello-no-compression')
      let seaBinary

      beforeAll(async () => {
        await fs.mkdir(testDir, { recursive: true })

        // Create hello-world JavaScript.
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `console.log('Hello from uncompressed SEA!');\nconsole.log('Compression: disabled');\n`,
        )

        // Create SEA config with compression explicitly disabled.
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify(
            {
              main: 'app.js',
              output: 'app.blob',
              disableExperimentalSEAWarning: true,
              useCodeCache: true,
              // Explicitly disable compression
              useCompression: false,
            },
            null,
            2,
          ),
        )

        // SEA blob will be generated by binject from sea-config.json

        // Copy smol binary for injection.
        seaBinary = path.join(testDir, 'hello-no-compression')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await fs.chmod(seaBinary, 0o755)

        // Inject SEA blob.
        const injectResult = await runBinject(
          seaBinary,
          'NODE_SEA_BLOB',
          'sea-config.json',
          {
            testDir,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
          },
        )

        expect(injectResult.code).toBe(0)
      })

      it('should execute and output hello-world message', async () => {
        const result = await spawn(seaBinary, [], {
          cwd: testDir,
        })

        expect(result.code).toBe(0)
        expect(result.stdout).toContain('Hello from uncompressed SEA!')
        expect(result.stdout).toContain('Compression: disabled')
      })
    })
  },
)
