/**
 * @fileoverview Tests for VFS (Virtual Filesystem) support with TAR/TAR.GZ archives.
 *
 * Tests:
 * - VFS initialization and node:smol-vfs module
 * - TAR archive parsing (USTAR, PAX, GNU)
 * - GZIP decompression
 * - SEA + VFS dual resource injection
 * - File extraction to ~/.socket/_dlx/<hash>/
 * - fs module integration
 *
 * Note: These tests require a built smol binary at build/{dev,prod}/out/Final/node/.
 * Run `pnpm build --dev` first to create the binary.
 */

import { existsSync, promises as fs } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { makeExecutable } from 'build-infra/lib/build-helpers'

import { safeDelete, safeMkdir } from '@socketsecurity/lib/fs'
import { spawn } from '@socketsecurity/lib/spawn'

import { MACHO_SEGMENT_NODE_SEA } from '../../../bin-infra/test/helpers/segment-names.mts'
import { SMOL_VFS_BLOB, runBinject } from '../helpers/binject.mts'
import { getLatestFinalBinary } from '../paths.mts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Get the latest Final binary from build/{dev,prod}/out/Final/node/
// This is the production binary suitable for injection and execution
const finalBinaryPath = getLatestFinalBinary()

// Skip all tests if no final binary is available
const skipTests = !finalBinaryPath || !existsSync(finalBinaryPath)

// Test tmp directory
const testTmpDir = path.join(os.tmpdir(), 'socket-btm-vfs-tests')

// Use sequential execution to avoid any remaining resource contention
describe.sequential.skipIf(skipTests)(
  'vFS (Virtual Filesystem) support',
  () => {
    const createdCacheDirs = []

    beforeAll(async () => {
      await safeMkdir(testTmpDir)
    })

    afterAll(async () => {
      await safeDelete(testTmpDir)

      // Cleanup all VFS cache directories created during tests
      const cleanupPromises = []
      for (const cacheDir of createdCacheDirs) {
        if (existsSync(cacheDir)) {
          cleanupPromises.push(safeDelete(cacheDir))
        }
      }
      await Promise.allSettled(cleanupPromises)
    })

    describe('sEA fuse injection', () => {
      it('should support NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 sentinel', async () => {
        const testDir = path.join(testTmpDir, 'sea-fuse')
        await safeMkdir(testDir)

        // Create test app
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(appJs, `console.log('SEA fuse works');`)

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Generate blob
        // SEA blob will be generated by binject from sea-config.json

        // Copy binary
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        // Inject with correct fuse (binject generates blob from config)
        const injectResult = await runBinject(
          seaBinary,
          'NODE_SEA_BLOB',
          'sea-config.json',
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )
        expect(injectResult.code).toBe(0)

        // Test execution
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('SEA fuse works')
      })
    })

    describe('vFS TAR archive creation', () => {
      it('should create uncompressed TAR archive', async () => {
        const testDir = path.join(testTmpDir, 'tar-uncompressed')
        await safeMkdir(testDir)

        // Create test files
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'hello.txt'), 'Hello VFS')
        await fs.writeFile(path.join(vfsDir, 'data.json'), '{"test":true}')

        // Create subdirectory
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'Nested')

        // Create TAR
        const tarPath = path.join(testDir, 'vfs.tar')
        const tarResult = await spawn(
          'tar',
          ['cf', tarPath, '-C', vfsDir, '.'],
          {
            cwd: testDir,
          },
        )
        expect(tarResult.code).toBe(0)
        expect(existsSync(tarPath)).toBeTruthy()

        // Verify TAR contents
        const listResult = await spawn('tar', ['tf', tarPath])
        expect(listResult.stdout).toContain('hello.txt')
        expect(listResult.stdout).toContain('data.json')
        expect(listResult.stdout).toContain('subdir/nested.txt')
      })

      it('should create compressed TAR.GZ archive', async () => {
        const testDir = path.join(testTmpDir, 'tar-compressed')
        await safeMkdir(testDir)

        // Create test files
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'large.txt'), 'X'.repeat(10_000))

        // Create TAR.GZ
        const tarGzPath = path.join(testDir, 'vfs.tar.gz')
        const tarResult = await spawn(
          'tar',
          ['czf', tarGzPath, '-C', vfsDir, '.'],
          { cwd: testDir },
        )
        expect(tarResult.code).toBe(0)
        expect(existsSync(tarGzPath)).toBeTruthy()

        // Verify compression (should be smaller)
        const tarSize =
          (await fs.stat(path.join(testDir, '../tar-uncompressed/vfs.tar')))
            .size || 10_000
        const tarGzSize = (await fs.stat(tarGzPath)).size
        expect(tarGzSize).toBeLessThan(tarSize)
      })
    })

    describe('vFS + SEA dual resource injection', () => {
      it(`should inject both NODE_SEA_BLOB and ${SMOL_VFS_BLOB}`, async () => {
        const testDir = path.join(testTmpDir, 'dual-injection')
        await safeMkdir(testDir)

        // Create SEA app that reads from VFS
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')
const path = require('path')

// Check VFS using node:smol-vfs module
const smolVfs = require('node:smol-vfs')

if (smolVfs.hasVFS()) {
  console.log('VFS_AVAILABLE')
  console.log('VFS_INITIALIZED')
  console.log('VFS_SIZE=' + smolVfs.size())
} else {
  console.log('VFS_NOT_AVAILABLE')
}
`,
        )

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Generate SEA blob
        // SEA blob will be generated by binject from sea-config.json

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'VFS file content')

        // Create VFS TAR (disable macOS resource forks)
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Copy binary
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        // Inject both SEA and VFS in a single operation
        const injectResult = await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )
        expect(injectResult.code).toBe(0)

        // Test execution
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('VFS_AVAILABLE')
        expect(execResult.stdout).toContain('VFS_INITIALIZED')
        expect(execResult.stdout).toContain('VFS_SIZE=')
      })
    })

    describe('vFS extraction to ~/.socket/_dlx/', () => {
      it('should extract VFS to cache directory on first run', async () => {
        const testDir = path.join(testTmpDir, 'vfs-extraction')
        await safeMkdir(testDir)

        // Create SEA app that extracts VFS files
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')
const path = require('path')
const { createHash } = require('crypto')
const os = require('os')
const smolVfs = require('node:smol-vfs')

// VFS extraction logic using node:smol-vfs module
const DLX_DIR = path.join(os.homedir(), '.socket', '_dlx')

async function extractVFS() {
  if (!smolVfs.hasVFS()) {
    console.log('NO_VFS')
    return
  }

  // Get VFS config for cache directory calculation
  const cfg = smolVfs.config()
  if (!cfg.available) {
    console.log('EMPTY_VFS')
    return
  }

  // List files to calculate content hash
  const files = smolVfs.listFiles()
  const contentHash = createHash('sha256')
  for (const file of files) {
    const content = smolVfs.readFileSync('/snapshot/' + file)
    contentHash.update(content)
  }
  const hash = contentHash.digest('hex').slice(0, 16)
  const cacheDir = path.join(DLX_DIR, hash)

  console.log('CACHE_DIR=' + cacheDir)

  // Check if already extracted
  if (fs.existsSync(cacheDir)) {
    console.log('CACHE_HIT')
    return
  }

  // Create cache directory
  fs.mkdirSync(cacheDir, { recursive: true })

  // Extract all files using node:smol-vfs
  let extracted = 0
  for (const file of files) {
    const content = smolVfs.readFileSync('/snapshot/' + file)
    const targetPath = path.join(cacheDir, file)
    fs.mkdirSync(path.dirname(targetPath), { recursive: true })
    fs.writeFileSync(targetPath, content)
    extracted++
  }

  console.log('EXTRACTED=' + extracted)
}

extractVFS().catch(err => {
  console.error('ERROR=' + err.message)
  process.exit(1)
})
`,
        )

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // SEA blob will be generated by binject from sea-config.json

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'file1.txt'), 'Content 1')
        await fs.writeFile(path.join(vfsDir, 'file2.txt'), 'Content 2')
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(
          path.join(vfsDir, 'subdir', 'file3.txt'),
          'Content 3',
        )

        // Create VFS TAR (disable macOS resource forks)
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Copy and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        // First run: should extract
        const firstRun = await spawn(seaBinary, [])
        expect(firstRun.code).toBe(0)
        expect(firstRun.stdout).toContain('CACHE_DIR=')
        expect(firstRun.stdout).toContain('EXTRACTED=3')

        // Extract cache directory from output
        const cacheDirMatch = firstRun.stdout.match(/CACHE_DIR=(.+)/)
        expect(cacheDirMatch).toBeTruthy()
        const cacheDir = cacheDirMatch[1].trim()
        createdCacheDirs.push(cacheDir)

        // Verify extraction
        expect(existsSync(cacheDir)).toBeTruthy()
        expect(existsSync(path.join(cacheDir, 'file1.txt'))).toBeTruthy()
        expect(existsSync(path.join(cacheDir, 'file2.txt'))).toBeTruthy()
        expect(
          existsSync(path.join(cacheDir, 'subdir', 'file3.txt')),
        ).toBeTruthy()

        // Verify content
        const content1 = await fs.readFile(
          path.join(cacheDir, 'file1.txt'),
          'utf8',
        )
        expect(content1).toBe('Content 1')

        // Second run: should hit cache
        const secondRun = await spawn(seaBinary, [])
        expect(secondRun.code).toBe(0)
        expect(secondRun.stdout).toContain('CACHE_HIT')
      })
    })

    describe('vFS TAR format support', () => {
      it('should support .tar (uncompressed) format', async () => {
        const testDir = path.join(testTmpDir, 'tar-format')
        await safeMkdir(testDir)

        // Create SEA app that reads from VFS
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const smolVfs = require('node:smol-vfs')
if (smolVfs.hasVFS()) {
  console.log('TAR_FORMAT=success')
  console.log('VFS_SIZE=' + smolVfs.size())
}
`,
        )

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'TAR format test')

        // Create uncompressed TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('TAR_FORMAT=success')
      })

      it('should support .tgz (gzip-compressed TAR) format', async () => {
        const testDir = path.join(testTmpDir, 'tgz-format')
        await safeMkdir(testDir)

        // Create SEA app that reads from VFS
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const smolVfs = require('node:smol-vfs')
if (smolVfs.hasVFS()) {
  console.log('TGZ_FORMAT=success')
  console.log('VFS_SIZE=' + smolVfs.size())
}
`,
        )

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'TGZ format test')

        // Create gzip-compressed TAR (.tgz)
        const vfsTgz = path.join(testDir, 'vfs.tgz')
        await spawn('tar', ['czf', vfsTgz, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTgz },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('TGZ_FORMAT=success')
      })

      it('should support PAX extended headers for long filenames', async () => {
        const testDir = path.join(testTmpDir, 'tar-pax')
        await safeMkdir(testDir)

        // Create file with long name (150 chars)
        // Note: macOS filesystem limits filenames to 255 bytes, but USTAR format
        // only supports 100 chars, so 150 chars requires PAX extended headers
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        const longName = `${'a'.repeat(150)}.txt`
        await fs.writeFile(path.join(vfsDir, longName), 'Long name content')

        // Create TAR with PAX format
        const tarPath = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', tarPath, '--format=posix', '-C', vfsDir, '.'])

        expect(existsSync(tarPath)).toBeTruthy()

        // Verify TAR contains long filename
        const listResult = await spawn('tar', ['tf', tarPath])
        expect(listResult.stdout).toContain(longName)
      })
    })

    describe('vFS extraction path validation', () => {
      it('should use SHA-256 hash (16 hex chars) for cache directory', async () => {
        const testDir = path.join(testTmpDir, 'vfs-hash-validation')
        await safeMkdir(testDir)

        // Create SEA app that validates hash format
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const smolVfs = require('node:smol-vfs')
if (smolVfs.hasVFS()) {
  const { createHash } = require('crypto')
  // Calculate hash from VFS files content
  const files = smolVfs.listFiles()
  const contentHash = createHash('sha256')
  for (const file of files) {
    const content = smolVfs.readFileSync('/snapshot/' + file)
    contentHash.update(content)
  }
  const fullHash = contentHash.digest('hex')
  const shortHash = fullHash.slice(0, 16)

  console.log('FULL_HASH_LENGTH=' + fullHash.length)
  console.log('SHORT_HASH_LENGTH=' + shortHash.length)
  console.log('SHORT_HASH=' + shortHash)

  // Validate it's hex
  const isHex = /^[0-9a-f]+$/.test(shortHash)
  console.log('IS_HEX=' + isHex)
}
`,
        )

        // Create and inject VFS
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        await spawn(
          finalBinaryPath,
          ['--experimental-sea-config', 'sea-config.json'],
          { cwd: testDir },
        )

        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'test')

        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'])

        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          { testDir },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('FULL_HASH_LENGTH=64')
        expect(execResult.stdout).toContain('SHORT_HASH_LENGTH=16')
        expect(execResult.stdout).toContain('IS_HEX=true')

        // Validate hash format
        const hashMatch = execResult.stdout.match(/SHORT_HASH=([\da-f]{16})/)
        expect(hashMatch).toBeTruthy()
      })

      it('should match compression extraction pattern structure', () => {
        // VFS: <cache>/<sha256-16chars>/
        const vfsPattern = /^[\da-f]{16}$/

        // Compression: <cache>/<sha512-16chars>-<platform>-<arch>/
        const compressionPattern =
          /^[\da-f]{16}-(macos|linux|windows)-(x64|arm64|ia32|arm)$/

        // VFS uses simpler hash-only pattern
        expect('a1b2c3d4e5f67890'.match(vfsPattern)).toBeTruthy()
        expect('a1b2c3d4e5f67890'.match(compressionPattern)).toBeFalsy()

        // Compression uses hash-platform-arch pattern
        expect(
          'a1b2c3d4e5f67890-macos-arm64'.match(compressionPattern),
        ).toBeTruthy()
        expect('a1b2c3d4e5f67890-macos-arm64'.match(vfsPattern)).toBeFalsy()
      })
    })

    describe('directory extraction with smolVfs.mountSync()', () => {
      it('should recursively extract directories using mountSync()', async () => {
        const testDir = path.join(testTmpDir, 'mount-directory')
        await safeMkdir(testDir)

        // Create SEA app that uses smolVfs.mountSync() to extract directories
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')
const path = require('path')
const smolVfs = require('node:smol-vfs')

// Test smolVfs.mountSync() API for directory extraction
if (smolVfs.hasVFS() && typeof smolVfs.mountSync === 'function') {
  try {
    // Test 1: Mount directory WITHOUT trailing slash
    const dir1 = smolVfs.mountSync('/snapshot/node_modules/test-package')
    console.log('DIR1_PATH=' + dir1)

    // Verify directory was extracted
    const dir1Exists = fs.existsSync(dir1)
    console.log('DIR1_EXISTS=' + dir1Exists)

    // Test 2: Mount directory WITH trailing slash (should work identically)
    const dir2 = smolVfs.mountSync('/snapshot/node_modules/test-package/')
    console.log('DIR2_PATH=' + dir2)
    console.log('PATHS_MATCH=' + (dir1 === dir2))

    // Test 3: Verify all files were extracted recursively
    const indexPath = path.join(dir1, 'index.js')
    const nestedPath = path.join(dir1, 'subdir', 'nested.js')

    console.log('INDEX_EXISTS=' + fs.existsSync(indexPath))
    console.log('NESTED_EXISTS=' + fs.existsSync(nestedPath))

    // Test 4: Verify file contents
    const indexContent = fs.readFileSync(indexPath, 'utf8')
    console.log('INDEX_CONTENT=' + indexContent.trim())

    const nestedContent = fs.readFileSync(nestedPath, 'utf8')
    console.log('NESTED_CONTENT=' + nestedContent.trim())

    // Test 5: Mount with backslashes (should normalize automatically)
    const dir3 = smolVfs.mountSync('\\\\snapshot\\\\node_modules\\\\test-package')
    console.log('BACKSLASH_PATHS_MATCH=' + (dir1 === dir3))

    // Test 6: Mount with backslashes AND trailing backslash (edge case)
    const dir4 = smolVfs.mountSync('\\\\snapshot\\\\node_modules\\\\test-package\\\\')
    console.log('BACKSLASH_TRAILING_PATHS_MATCH=' + (dir1 === dir4))

    console.log('MOUNT_DIRECTORY_SUCCESS')
  } catch (err) {
    console.log('MOUNT_ERROR=' + err.message)
  }
} else {
  console.log('NO_SMOL_MOUNT_API')
}
`,
        )

        // Create VFS content with directory structure
        const vfsDir = path.join(testDir, 'vfs-content')
        const pkgDir = path.join(vfsDir, 'node_modules', 'test-package')
        await safeMkdir(pkgDir)
        await safeMkdir(path.join(pkgDir, 'subdir'))

        await fs.writeFile(
          path.join(pkgDir, 'index.js'),
          'module.exports = "hello"',
        )
        await fs.writeFile(
          path.join(pkgDir, 'package.json'),
          '{"name":"test-package"}',
        )
        await fs.writeFile(
          path.join(pkgDir, 'subdir', 'nested.js'),
          'module.exports = "nested"',
        )

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        // Execute and verify
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('MOUNT_DIRECTORY_SUCCESS')
        expect(execResult.stdout).toContain('DIR1_EXISTS=true')
        expect(execResult.stdout).toContain('PATHS_MATCH=true')
        expect(execResult.stdout).toContain('INDEX_EXISTS=true')
        expect(execResult.stdout).toContain('NESTED_EXISTS=true')
        expect(execResult.stdout).toContain(
          'INDEX_CONTENT=module.exports = "hello"',
        )
        expect(execResult.stdout).toContain(
          'NESTED_CONTENT=module.exports = "nested"',
        )
        expect(execResult.stdout).toContain('BACKSLASH_PATHS_MATCH=true')
        expect(execResult.stdout).toContain(
          'BACKSLASH_TRAILING_PATHS_MATCH=true',
        )
      })
    })

    describe('vFS file permissions', () => {
      it('should preserve executable permissions (0755) when extracting from VFS', async () => {
        const testDir = path.join(testTmpDir, 'vfs-permissions')
        await safeMkdir(testDir)

        // Create SEA app that extracts files and checks their permissions
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')
const path = require('path')
const smolVfs = require('node:smol-vfs')

// Test that executable permissions are preserved
if (smolVfs.hasVFS() && typeof smolVfs.mountSync === 'function') {
  try {
    // Mount directory containing executable
    const dir = smolVfs.mountSync('/snapshot/bin')
    console.log('DIR=' + dir)

    // Check executable file permissions
    const pythonPath = path.join(dir, 'python')
    const stats = fs.statSync(pythonPath)
    const mode = (stats.mode & 0o777).toString(8)
    console.log('PYTHON_MODE=' + mode)
    console.log('PYTHON_EXECUTABLE=' + ((stats.mode & 0o100) !== 0))

    // Check regular file permissions
    const configPath = path.join(dir, 'config.txt')
    const configStats = fs.statSync(configPath)
    const configMode = (configStats.mode & 0o777).toString(8)
    console.log('CONFIG_MODE=' + configMode)

    console.log('PERMISSIONS_TEST_SUCCESS')
  } catch (err) {
    console.log('PERMISSIONS_ERROR=' + err.message)
  }
} else {
  console.log('NO_SMOL_MOUNT_API')
}
`,
        )

        // Create VFS content with executable and regular file
        const vfsDir = path.join(testDir, 'vfs-content')
        const binDir = path.join(vfsDir, 'bin')
        await safeMkdir(binDir)

        // Create fake Python binary
        const pythonPath = path.join(binDir, 'python')
        await fs.writeFile(pythonPath, '#!/usr/bin/env python3\nprint("hello")')
        await makeExecutable(pythonPath)

        // Create regular config file
        const configPath = path.join(binDir, 'config.txt')
        await fs.writeFile(configPath, 'key=value')
        await fs.chmod(configPath, 0o644)

        // Create VFS TAR that preserves permissions
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Verify TAR contains correct permissions
        const tarListResult = await spawn('tar', ['tvf', vfsTar])
        expect(tarListResult.stdout).toContain('rwxr-xr-x')
        expect(tarListResult.stdout).toContain('python')
        expect(tarListResult.stdout).toContain('rw-r--r--')
        expect(tarListResult.stdout).toContain('config.txt')

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        // Execute and verify permissions are preserved
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('PERMISSIONS_TEST_SUCCESS')
        expect(execResult.stdout).toContain('PYTHON_MODE=755')
        expect(execResult.stdout).toContain('PYTHON_EXECUTABLE=true')
        expect(execResult.stdout).toContain('CONFIG_MODE=644')
      })
    })

    describe('vFS fs shim enhancements', () => {
      it('should support async fs.readFile() callback', async () => {
        const testDir = path.join(testTmpDir, 'vfs-async-readfile')
        await safeMkdir(testDir)

        // Create SEA app that tests async readFile
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

// Test async readFile with callback on VFS path
fs.readFile('/snapshot/test.txt', 'utf8', (err, data) => {
  if (err) {
    console.log('ASYNC_READFILE_ERROR=' + err.code)
  } else {
    console.log('ASYNC_READFILE_DATA=' + data)
  }
})
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'async-test-content')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain(
          'ASYNC_READFILE_DATA=async-test-content',
        )
      })

      it('should support fs.promises.readFile()', async () => {
        const testDir = path.join(testTmpDir, 'vfs-promises-readfile')
        await safeMkdir(testDir)

        // Create SEA app that tests promises readFile
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs').promises

async function test() {
  try {
    const data = await fs.readFile('/snapshot/test.txt', 'utf8')
    console.log('PROMISE_READFILE_DATA=' + data)
  } catch (err) {
    console.log('PROMISE_READFILE_ERROR=' + err.code)
  }
}

test()
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(
          path.join(vfsDir, 'test.txt'),
          'promise-test-content',
        )

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain(
          'PROMISE_READFILE_DATA=promise-test-content',
        )
      })

      it('should support async fs.stat() and fs.readdir() callbacks', async () => {
        const testDir = path.join(testTmpDir, 'vfs-async-stat-readdir')
        await safeMkdir(testDir)

        // Create SEA app that tests async stat and readdir
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

let results = []

// Test async stat
fs.stat('/snapshot/test.txt', (err, stats) => {
  if (err) {
    results.push('STAT_ERROR=' + err.code)
  } else {
    results.push('STAT_IS_FILE=' + stats.isFile())
    results.push('STAT_SIZE=' + stats.size)
  }

  // Test async readdir after stat completes
  fs.readdir('/snapshot', (err2, files) => {
    if (err2) {
      results.push('READDIR_ERROR=' + err2.code)
    } else {
      results.push('READDIR_FILES=' + files.join(','))
    }
    // Print all results
    console.log(results.join('\\n'))
  })
})
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'hello')
        await fs.writeFile(path.join(vfsDir, 'other.txt'), 'world')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('STAT_IS_FILE=true')
        expect(execResult.stdout).toContain('STAT_SIZE=5')
        expect(execResult.stdout).toContain('READDIR_FILES=')
        expect(execResult.stdout).toMatch(/test\.txt/)
      })

      it('should throw EROFS for write operations on VFS paths', async () => {
        const testDir = path.join(testTmpDir, 'vfs-erofs')
        await safeMkdir(testDir)

        // Create SEA app that tests EROFS errors
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test writeFileSync throws EROFS
try {
  fs.writeFileSync('/snapshot/test.txt', 'data')
  results.push('WRITE_SUCCESS')
} catch (err) {
  results.push('WRITE_ERROR=' + err.code)
}

// Test unlinkSync throws EROFS
try {
  fs.unlinkSync('/snapshot/test.txt')
  results.push('UNLINK_SUCCESS')
} catch (err) {
  results.push('UNLINK_ERROR=' + err.code)
}

// Test mkdirSync throws EROFS
try {
  fs.mkdirSync('/snapshot/newdir')
  results.push('MKDIR_SUCCESS')
} catch (err) {
  results.push('MKDIR_ERROR=' + err.code)
}

// Test renameSync throws EROFS
try {
  fs.renameSync('/snapshot/test.txt', '/snapshot/new.txt')
  results.push('RENAME_SUCCESS')
} catch (err) {
  results.push('RENAME_ERROR=' + err.code)
}

console.log(results.join('\\n'))
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'content')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('WRITE_ERROR=EROFS')
        expect(execResult.stdout).toContain('UNLINK_ERROR=EROFS')
        expect(execResult.stdout).toContain('MKDIR_ERROR=EROFS')
        expect(execResult.stdout).toContain('RENAME_ERROR=EROFS')
      })

      it('should support realpathSync.native on VFS paths', async () => {
        const testDir = path.join(testTmpDir, 'vfs-realpath-native')
        await safeMkdir(testDir)

        // Create SEA app that tests realpathSync.native
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test realpathSync.native on existing VFS path
try {
  const result = fs.realpathSync.native('/snapshot/test.txt')
  results.push('REALPATH_NATIVE=' + result)
} catch (err) {
  results.push('REALPATH_NATIVE_ERROR=' + err.code)
}

// Test realpathSync.native on non-existent VFS path
try {
  fs.realpathSync.native('/snapshot/nonexistent.txt')
  results.push('REALPATH_NATIVE_NOENT=no_error')
} catch (err) {
  results.push('REALPATH_NATIVE_NOENT=' + err.code)
}

console.log(results.join('\\n'))
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'content')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain(
          'REALPATH_NATIVE=/snapshot/test.txt',
        )
        expect(execResult.stdout).toContain('REALPATH_NATIVE_NOENT=ENOENT')
      })

      it('should work with captured fs references (handler pattern)', async () => {
        const testDir = path.join(testTmpDir, 'vfs-captured-refs')
        await safeMkdir(testDir)

        // Create SEA app that captures fs references before VFS is installed
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
// Capture fs.readFileSync reference BEFORE any VFS initialization
const { readFileSync } = require('fs')

// Also capture the method directly
const fs = require('fs')
const capturedReadFileSync = fs.readFileSync

// Now use the captured references to read from VFS
try {
  // Test destructured reference
  const data1 = readFileSync('/snapshot/test.txt', 'utf8')
  console.log('CAPTURED_DESTRUCTURED=' + data1)

  // Test captured method reference
  const data2 = capturedReadFileSync('/snapshot/test.txt', 'utf8')
  console.log('CAPTURED_METHOD=' + data2)
} catch (err) {
  console.log('CAPTURED_ERROR=' + err.message)
}
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'captured-works')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain(
          'CAPTURED_DESTRUCTURED=captured-works',
        )
        expect(execResult.stdout).toContain('CAPTURED_METHOD=captured-works')
      })

      it('should support async fs.access() callback', async () => {
        const testDir = path.join(testTmpDir, 'vfs-async-access')
        await safeMkdir(testDir)

        // Create SEA app that tests async access
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test access on existing VFS path
fs.access('/snapshot/test.txt', fs.constants.R_OK, (err) => {
  if (err) {
    results.push('ACCESS_EXIST_ERROR=' + err.code)
  } else {
    results.push('ACCESS_EXIST_OK=true')
  }

  // Test access on non-existent VFS path
  fs.access('/snapshot/nonexistent.txt', fs.constants.R_OK, (err2) => {
    if (err2) {
      results.push('ACCESS_NOENT_ERROR=' + err2.code)
    } else {
      results.push('ACCESS_NOENT_OK=true')
    }
    console.log(results.join('\\n'))
  })
})
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'content')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('ACCESS_EXIST_OK=true')
        expect(execResult.stdout).toContain('ACCESS_NOENT_ERROR=ENOENT')
      })

      it('should support async fs.lstat() callback', async () => {
        const testDir = path.join(testTmpDir, 'vfs-async-lstat')
        await safeMkdir(testDir)

        // Create SEA app that tests async lstat
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test lstat on existing VFS file
fs.lstat('/snapshot/test.txt', (err, stats) => {
  if (err) {
    results.push('LSTAT_ERROR=' + err.code)
  } else {
    results.push('LSTAT_IS_FILE=' + stats.isFile())
    results.push('LSTAT_IS_SYMLINK=' + stats.isSymbolicLink())
    results.push('LSTAT_SIZE=' + stats.size)
  }
  console.log(results.join('\\n'))
})
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'hello')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('LSTAT_IS_FILE=true')
        expect(execResult.stdout).toContain('LSTAT_IS_SYMLINK=false')
        expect(execResult.stdout).toContain('LSTAT_SIZE=5')
      })

      it('should support fs.promises.stat() and fs.promises.readdir()', async () => {
        const testDir = path.join(testTmpDir, 'vfs-promises-stat-readdir')
        await safeMkdir(testDir)

        // Create SEA app that tests promise stat and readdir
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs').promises

async function test() {
  const results = []

  try {
    // Test promises stat
    const stats = await fs.stat('/snapshot/test.txt')
    results.push('PROMISE_STAT_IS_FILE=' + stats.isFile())
    results.push('PROMISE_STAT_SIZE=' + stats.size)

    // Test promises readdir
    const entries = await fs.readdir('/snapshot')
    results.push('PROMISE_READDIR_COUNT=' + entries.length)
    results.push('PROMISE_READDIR_HAS_FILE=' + entries.includes('test.txt'))
  } catch (err) {
    results.push('PROMISE_ERROR=' + err.code)
  }

  console.log(results.join('\\n'))
}

test()
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'hello world')
        await fs.writeFile(path.join(vfsDir, 'other.txt'), 'other')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('PROMISE_STAT_IS_FILE=true')
        expect(execResult.stdout).toContain('PROMISE_STAT_SIZE=11')
        expect(execResult.stdout).toContain('PROMISE_READDIR_HAS_FILE=true')
      })

      it('should support fs.promises.access() and fs.promises.realpath()', async () => {
        const testDir = path.join(testTmpDir, 'vfs-promises-access-realpath')
        await safeMkdir(testDir)

        // Create SEA app that tests promise access and realpath
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs').promises
const { constants } = require('fs')

async function test() {
  const results = []

  try {
    // Test promises access
    await fs.access('/snapshot/test.txt', constants.R_OK)
    results.push('PROMISE_ACCESS_OK=true')
  } catch (err) {
    results.push('PROMISE_ACCESS_ERROR=' + err.code)
  }

  try {
    // Test promises realpath
    const real = await fs.realpath('/snapshot/test.txt')
    results.push('PROMISE_REALPATH=' + real)
  } catch (err) {
    results.push('PROMISE_REALPATH_ERROR=' + err.code)
  }

  try {
    // Test promises access on non-existent path
    await fs.access('/snapshot/nonexistent.txt', constants.R_OK)
    results.push('PROMISE_ACCESS_NOENT_OK=true')
  } catch (err) {
    results.push('PROMISE_ACCESS_NOENT_ERROR=' + err.code)
  }

  console.log(results.join('\\n'))
}

test()
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'content')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('PROMISE_ACCESS_OK=true')
        expect(execResult.stdout).toContain(
          'PROMISE_REALPATH=/snapshot/test.txt',
        )
        expect(execResult.stdout).toContain('PROMISE_ACCESS_NOENT_ERROR=ENOENT')
      })

      it('should support fs.existsSync() on VFS paths', async () => {
        const testDir = path.join(testTmpDir, 'vfs-exists-sync')
        await safeMkdir(testDir)

        // Create SEA app that tests existsSync
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test existsSync on existing VFS path
results.push('EXISTS_FILE=' + fs.existsSync('/snapshot/test.txt'))
results.push('EXISTS_DIR=' + fs.existsSync('/snapshot/subdir'))
results.push('EXISTS_NOENT=' + fs.existsSync('/snapshot/nonexistent.txt'))

console.log(results.join('\\n'))
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('EXISTS_FILE=true')
        expect(execResult.stdout).toContain('EXISTS_DIR=true')
        expect(execResult.stdout).toContain('EXISTS_NOENT=false')
      })

      it('should support fs.readdirSync() with withFileTypes option', async () => {
        const testDir = path.join(testTmpDir, 'vfs-readdir-filetypes')
        await safeMkdir(testDir)

        // Create SEA app that tests readdirSync withFileTypes
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test readdirSync with withFileTypes
const entries = fs.readdirSync('/snapshot', { withFileTypes: true })
for (const entry of entries) {
  results.push('ENTRY=' + entry.name + ':isFile=' + entry.isFile() + ':isDir=' + entry.isDirectory())
}

console.log(results.join('\\n'))
`,
        )

        // Create VFS content with mixed files and dirs
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'file.txt'), 'content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toMatch(
          /ENTRY=file\.txt:isFile=true:isDir=false/,
        )
        expect(execResult.stdout).toMatch(
          /ENTRY=subdir:isFile=false:isDir=true/,
        )
      })

      it('should throw EISDIR when reading directory as file', async () => {
        const testDir = path.join(testTmpDir, 'vfs-eisdir')
        await safeMkdir(testDir)

        // Create SEA app that tests EISDIR error
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

try {
  fs.readFileSync('/snapshot/subdir')
  console.log('READ_SUCCESS')
} catch (err) {
  console.log('READ_ERROR=' + err.code)
}
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'subdir', 'file.txt'), 'content')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('READ_ERROR=EISDIR')
      })
    })

    describe('vFS symlink support', () => {
      it('should support fs.lstatSync() and fs.readlinkSync() on symlinks', async () => {
        const testDir = path.join(testTmpDir, 'vfs-symlinks')
        await safeMkdir(testDir)

        // Create SEA app that tests symlink operations
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test lstatSync on symlink - should NOT follow
const symlinkStats = fs.lstatSync('/snapshot/link-to-file.txt')
results.push('LSTAT_IS_SYMLINK=' + symlinkStats.isSymbolicLink())
results.push('LSTAT_IS_FILE=' + symlinkStats.isFile())
results.push('LSTAT_IS_DIRECTORY=' + symlinkStats.isDirectory())

// Test readlinkSync - should return target path
const linkTarget = fs.readlinkSync('/snapshot/link-to-file.txt')
results.push('READLINK_TARGET=' + linkTarget)

// Test lstatSync on directory symlink
const dirLinkStats = fs.lstatSync('/snapshot/link-to-dir')
results.push('DIR_LSTAT_IS_SYMLINK=' + dirLinkStats.isSymbolicLink())
results.push('DIR_LSTAT_IS_DIRECTORY=' + dirLinkStats.isDirectory())

// Test readlinkSync on directory symlink
const dirLinkTarget = fs.readlinkSync('/snapshot/link-to-dir')
results.push('DIR_READLINK_TARGET=' + dirLinkTarget)

// Test lstatSync on regular file (should NOT be symlink)
const fileStats = fs.lstatSync('/snapshot/target.txt')
results.push('FILE_LSTAT_IS_SYMLINK=' + fileStats.isSymbolicLink())
results.push('FILE_LSTAT_IS_FILE=' + fileStats.isFile())

console.log(results.join('\\n'))
`,
        )

        // Create VFS content with symlinks
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'target.txt'), 'target content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')

        // Create symlinks
        await fs.symlink('target.txt', path.join(vfsDir, 'link-to-file.txt'))
        await fs.symlink('subdir', path.join(vfsDir, 'link-to-dir'))

        // Create VFS TAR with symlinks preserved (use -h to NOT follow symlinks)
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Verify TAR contains symlinks
        const tarListResult = await spawn('tar', ['tvf', vfsTar])
        expect(tarListResult.stdout).toContain('link-to-file.txt')
        expect(tarListResult.stdout).toContain('link-to-dir')

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('LSTAT_IS_SYMLINK=true')
        expect(execResult.stdout).toContain('LSTAT_IS_FILE=false')
        expect(execResult.stdout).toContain('LSTAT_IS_DIRECTORY=false')
        expect(execResult.stdout).toContain('READLINK_TARGET=target.txt')
        expect(execResult.stdout).toContain('DIR_LSTAT_IS_SYMLINK=true')
        expect(execResult.stdout).toContain('DIR_LSTAT_IS_DIRECTORY=false')
        expect(execResult.stdout).toContain('DIR_READLINK_TARGET=subdir')
        expect(execResult.stdout).toContain('FILE_LSTAT_IS_SYMLINK=false')
        expect(execResult.stdout).toContain('FILE_LSTAT_IS_FILE=true')
      })

      it('should throw EINVAL when readlinkSync is called on non-symlink', async () => {
        const testDir = path.join(testTmpDir, 'vfs-readlink-einval')
        await safeMkdir(testDir)

        // Create SEA app that tests EINVAL error
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test readlinkSync on regular file - should throw EINVAL
try {
  fs.readlinkSync('/snapshot/regular.txt')
  results.push('REGULAR_FILE_SUCCESS')
} catch (err) {
  results.push('REGULAR_FILE_ERROR=' + err.code)
}

// Test readlinkSync on directory - should throw EINVAL
try {
  fs.readlinkSync('/snapshot/subdir')
  results.push('DIRECTORY_SUCCESS')
} catch (err) {
  results.push('DIRECTORY_ERROR=' + err.code)
}

// Test readlinkSync on non-existent path - should throw ENOENT
try {
  fs.readlinkSync('/snapshot/nonexistent')
  results.push('NONEXISTENT_SUCCESS')
} catch (err) {
  results.push('NONEXISTENT_ERROR=' + err.code)
}

console.log(results.join('\\n'))
`,
        )

        // Create VFS content without symlinks
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'regular.txt'), 'regular content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('REGULAR_FILE_ERROR=EINVAL')
        expect(execResult.stdout).toContain('DIRECTORY_ERROR=EINVAL')
        expect(execResult.stdout).toContain('NONEXISTENT_ERROR=ENOENT')
      })

      it('should support async fs.readlink() callback', async () => {
        const testDir = path.join(testTmpDir, 'vfs-async-readlink')
        await safeMkdir(testDir)

        // Create SEA app that tests async readlink
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test async readlink on symlink
fs.readlink('/snapshot/link.txt', (err, target) => {
  if (err) {
    results.push('ASYNC_READLINK_ERROR=' + err.code)
  } else {
    results.push('ASYNC_READLINK_TARGET=' + target)
  }

  // Test async readlink on non-symlink (should get EINVAL)
  fs.readlink('/snapshot/regular.txt', (err2, target2) => {
    if (err2) {
      results.push('ASYNC_READLINK_EINVAL=' + err2.code)
    } else {
      results.push('ASYNC_READLINK_EINVAL_TARGET=' + target2)
    }
    console.log(results.join('\\n'))
  })
})
`,
        )

        // Create VFS content with symlink
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'regular.txt'), 'content')
        await fs.symlink('regular.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('ASYNC_READLINK_TARGET=regular.txt')
        expect(execResult.stdout).toContain('ASYNC_READLINK_EINVAL=EINVAL')
      })

      it('should support fs.promises.readlink()', async () => {
        const testDir = path.join(testTmpDir, 'vfs-promise-readlink')
        await safeMkdir(testDir)

        // Create SEA app that tests promise readlink
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs').promises

async function test() {
  const results = []

  try {
    // Test promise readlink on symlink
    const target = await fs.readlink('/snapshot/link.txt')
    results.push('PROMISE_READLINK_TARGET=' + target)
  } catch (err) {
    results.push('PROMISE_READLINK_ERROR=' + err.code)
  }

  try {
    // Test promise readlink on non-symlink (should get EINVAL)
    await fs.readlink('/snapshot/regular.txt')
    results.push('PROMISE_READLINK_EINVAL=no_error')
  } catch (err) {
    results.push('PROMISE_READLINK_EINVAL=' + err.code)
  }

  try {
    // Test promise readlink on non-existent (should get ENOENT)
    await fs.readlink('/snapshot/nonexistent')
    results.push('PROMISE_READLINK_ENOENT=no_error')
  } catch (err) {
    results.push('PROMISE_READLINK_ENOENT=' + err.code)
  }

  console.log(results.join('\\n'))
}

test()
`,
        )

        // Create VFS content with symlink
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'regular.txt'), 'content')
        await fs.symlink('regular.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain(
          'PROMISE_READLINK_TARGET=regular.txt',
        )
        expect(execResult.stdout).toContain('PROMISE_READLINK_EINVAL=EINVAL')
        expect(execResult.stdout).toContain('PROMISE_READLINK_ENOENT=ENOENT')
      })

      it('should support fs.readdirSync() with withFileTypes detecting symlinks', async () => {
        const testDir = path.join(testTmpDir, 'vfs-readdir-symlinks')
        await safeMkdir(testDir)

        // Create SEA app that tests readdir with symlinks
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test readdirSync with withFileTypes - should detect symlinks
const entries = fs.readdirSync('/snapshot', { withFileTypes: true })
for (const entry of entries) {
  const type = entry.isSymbolicLink() ? 'symlink' : entry.isDirectory() ? 'dir' : 'file'
  results.push('ENTRY=' + entry.name + ':type=' + type)
}

// Also test async lstat to verify symlink detection
fs.lstat('/snapshot/link.txt', (err, stats) => {
  if (err) {
    results.push('LSTAT_ERROR=' + err.code)
  } else {
    results.push('ASYNC_LSTAT_IS_SYMLINK=' + stats.isSymbolicLink())
  }
  console.log(results.join('\\n'))
})
`,
        )

        // Create VFS content with mixed file types including symlink
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'regular.txt'), 'content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')
        await fs.symlink('regular.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toMatch(/ENTRY=link\.txt:type=symlink/)
        expect(execResult.stdout).toMatch(/ENTRY=regular\.txt:type=file/)
        expect(execResult.stdout).toMatch(/ENTRY=subdir:type=dir/)
        expect(execResult.stdout).toContain('ASYNC_LSTAT_IS_SYMLINK=true')
      })

      it('should support fs.promises.lstat() on symlinks', async () => {
        const testDir = path.join(testTmpDir, 'vfs-promise-lstat')
        await safeMkdir(testDir)

        // Create SEA app that tests promise lstat
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs').promises

async function test() {
  const results = []

  try {
    // Test promise lstat on symlink
    const symlinkStats = await fs.lstat('/snapshot/link.txt')
    results.push('PROMISE_LSTAT_IS_SYMLINK=' + symlinkStats.isSymbolicLink())
    results.push('PROMISE_LSTAT_IS_FILE=' + symlinkStats.isFile())
  } catch (err) {
    results.push('PROMISE_LSTAT_ERROR=' + err.code)
  }

  try {
    // Test promise lstat on regular file
    const fileStats = await fs.lstat('/snapshot/regular.txt')
    results.push('PROMISE_FILE_LSTAT_IS_SYMLINK=' + fileStats.isSymbolicLink())
    results.push('PROMISE_FILE_LSTAT_IS_FILE=' + fileStats.isFile())
  } catch (err) {
    results.push('PROMISE_FILE_LSTAT_ERROR=' + err.code)
  }

  console.log(results.join('\\n'))
}

test()
`,
        )

        // Create VFS content with symlink
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'regular.txt'), 'content')
        await fs.symlink('regular.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('PROMISE_LSTAT_IS_SYMLINK=true')
        expect(execResult.stdout).toContain('PROMISE_LSTAT_IS_FILE=false')
        expect(execResult.stdout).toContain(
          'PROMISE_FILE_LSTAT_IS_SYMLINK=false',
        )
        expect(execResult.stdout).toContain('PROMISE_FILE_LSTAT_IS_FILE=true')
      })
    })

    describe('vFS glob support', () => {
      it('should support fs.globSync() on VFS paths', async () => {
        const testDir = path.join(testTmpDir, 'vfs-glob-sync')
        await safeMkdir(testDir)

        // Create SEA app that tests globSync
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test globSync on VFS with pattern
const txtFiles = fs.globSync('/snapshot/**/*.txt')
results.push('TXT_FILES=' + txtFiles.sort().join(','))

// Test globSync with cwd option
const allFiles = fs.globSync('**/*', { cwd: '/snapshot' })
results.push('ALL_FILES_COUNT=' + allFiles.length)

// Test that symlinks are included in glob results
const hasSymlink = allFiles.some(f => f === 'link.txt' || f.endsWith('/link.txt'))
results.push('SYMLINK_IN_RESULTS=' + hasSymlink)

console.log(results.join('\\n'))
`,
        )

        // Create VFS content with files and symlinks
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'file.txt'), 'content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')
        await fs.writeFile(path.join(vfsDir, 'other.js'), 'js content')
        await fs.symlink('file.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        // Should find .txt files including nested and symlink
        expect(execResult.stdout).toMatch(/TXT_FILES=.*file\.txt/)
        expect(execResult.stdout).toMatch(/TXT_FILES=.*nested\.txt/)
        expect(execResult.stdout).toContain('SYMLINK_IN_RESULTS=true')
      })

      it('should support fs.globSync() with withFileTypes option', async () => {
        const testDir = path.join(testTmpDir, 'vfs-glob-withfiletypes')
        await safeMkdir(testDir)

        // Create SEA app that tests globSync with withFileTypes
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const results = []

// Test globSync with withFileTypes
const entries = fs.globSync('/snapshot/*', { withFileTypes: true })

for (const entry of entries) {
  const type = entry.isSymbolicLink() ? 'symlink' : entry.isDirectory() ? 'dir' : 'file'
  results.push('GLOB_ENTRY=' + entry.name + ':' + type)
}

// Verify symlink detection works correctly
const symlinkEntry = entries.find(e => e.name === 'link.txt')
if (symlinkEntry) {
  results.push('SYMLINK_IS_SYMLINK=' + symlinkEntry.isSymbolicLink())
  results.push('SYMLINK_IS_FILE=' + symlinkEntry.isFile())
}

console.log(results.join('\\n'))
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'file.txt'), 'content')
        await fs.symlink('file.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toMatch(/GLOB_ENTRY=link\.txt:symlink/)
        expect(execResult.stdout).toMatch(/GLOB_ENTRY=file\.txt:file/)
        expect(execResult.stdout).toMatch(/GLOB_ENTRY=subdir:dir/)
        expect(execResult.stdout).toContain('SYMLINK_IS_SYMLINK=true')
        expect(execResult.stdout).toContain('SYMLINK_IS_FILE=false')
      })

      // Async glob captures fs/promises references at module load time, before
      // VFS shim installation. globSync works (uses shimmed fs methods directly).
      // TODO: fix by ensuring VFS shim installs before glob module loads.
      it.todo('should support async fs.glob() on VFS paths', async () => {
        const testDir = path.join(testTmpDir, 'vfs-glob-async')
        await safeMkdir(testDir)

        // Create SEA app that tests async glob
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

async function test() {
  const results = []

  // Test async glob with for-await
  const files = []
  for await (const file of fs.glob('/snapshot/**/*.txt')) {
    files.push(file)
  }
  results.push('ASYNC_GLOB_COUNT=' + files.length)
  results.push('ASYNC_GLOB_HAS_NESTED=' + files.some(f => f.includes('nested')))

  console.log(results.join('\\n'))
}

test()
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await safeMkdir(path.join(vfsDir, 'subdir'))
        await fs.writeFile(path.join(vfsDir, 'file.txt'), 'content')
        await fs.writeFile(path.join(vfsDir, 'subdir', 'nested.txt'), 'nested')
        await fs.symlink('file.txt', path.join(vfsDir, 'link.txt'))

        // Create VFS TAR
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )

        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        // Should find file.txt, nested.txt, and link.txt (symlink to .txt)
        expect(execResult.stdout).toMatch(/ASYNC_GLOB_COUNT=[23]/)
        expect(execResult.stdout).toContain('ASYNC_GLOB_HAS_NESTED=true')
      })
    })

    describe('vFS mode flags', () => {
      it('should support --vfs-on-disk mode (default)', async () => {
        const testDir = path.join(testTmpDir, 'vfs-on-disk')
        await safeMkdir(testDir)

        // Create SEA app
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const smolVfs = require('node:smol-vfs')
console.log('VFS_MODE=on-disk')
console.log('VFS_AVAILABLE=' + smolVfs.hasVFS())
`,
        )

        // Generate SEA blob (not needed for this test - using sea-config.json)

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'on-disk mode')

        // Create VFS TAR (disable macOS resource forks)
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject with --vfs-on-disk
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        const result = await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
            vfsMode: 'on-disk',
          },
        )
        expect(result.code).toBe(0)

        // Execute and verify
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('VFS_MODE=on-disk')
      })

      it('should support --vfs-in-memory mode', async () => {
        const testDir = path.join(testTmpDir, 'vfs-in-memory')
        await safeMkdir(testDir)

        // Create SEA app
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const smolVfs = require('node:smol-vfs')
console.log('VFS_MODE=in-memory')
console.log('VFS_AVAILABLE=' + smolVfs.hasVFS())
`,
        )

        // Create VFS content
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'in-memory mode')

        // Create VFS TAR (disable macOS resource forks)
        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        // Create SEA config
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Copy binary and inject with --vfs-in-memory
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        const result = await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
            vfsMode: 'in-memory',
          },
        )
        expect(result.code).toBe(0)

        // Execute and verify
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('VFS_MODE=in-memory')
      })

      it('should support --vfs-compat mode (no file bundling)', async () => {
        const testDir = path.join(testTmpDir, 'vfs-compat')
        await safeMkdir(testDir)

        // Create SEA app
        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const smolVfs = require('node:smol-vfs')
const process = require('node:process')

console.log('VFS_MODE=compat')
console.log('VFS_AVAILABLE=' + smolVfs.hasVFS())
`,
        )

        // Generate SEA blob
        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )
        await spawn(
          finalBinaryPath,
          ['--experimental-sea-config', 'sea-config.json'],
          { cwd: testDir },
        )

        // Copy binary and inject with --vfs-compat (no VFS file needed)
        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        const result = await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'app.blob', vfs: null },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
            vfsMode: 'compat',
          },
        )
        expect(result.code).toBe(0)

        // Execute and verify
        const execResult = await spawn(seaBinary, [])
        expect(execResult.code).toBe(0)
        expect(execResult.stdout).toContain('VFS_MODE=compat')
      })
    })

    describe('vFS path traversal protection', () => {
      it('should throw ENOENT for path traversal leaks via fs.readFileSync', async () => {
        const testDir = path.join(testTmpDir, 'vfs-traversal')
        await safeMkdir(testDir)

        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

// These paths must ALL throw ENOENT, never leak real files outside the VFS.
const leakPaths = [
  '/snapshot/../etc/passwd',
  '/snapshot/../../etc/shadow',
  '/snapshot/../../../.ssh/id_rsa',
  '/snapshot/node_modules/../../etc/passwd',
  '/snapshot/a/../../../etc/hosts',
  '/snapshot/..',
  '/snapshot/../',
]

let blocked = 0
let leaked = 0

for (const attack of leakPaths) {
  try {
    const data = fs.readFileSync(attack, 'utf8')
    // If we get here, the traversal was NOT blocked
    leaked++
    console.log('LEAKED:' + attack)
  } catch (err) {
    if (err.code === 'ENOENT') {
      blocked++
    } else {
      console.log('UNEXPECTED_ERROR:' + attack + ':' + err.code)
    }
  }
}

console.log('BLOCKED=' + blocked)
console.log('LEAKED=' + leaked)
console.log('TOTAL=' + leakPaths.length)

// Also verify existsSync returns false (not true via fallthrough)
for (const attack of leakPaths) {
  if (fs.existsSync(attack)) {
    console.log('EXISTS_LEAKED:' + attack)
  }
}

// Verify a valid VFS file still works
const smolVfs = require('node:smol-vfs')
if (smolVfs.hasVFS()) {
  try {
    const content = smolVfs.readFileSync('/snapshot/test.txt', 'utf8')
    console.log('VFS_READ_OK=' + content)
  } catch (err) {
    console.log('VFS_READ_FAIL=' + err.code)
  }
}

console.log('TRAVERSAL_TEST_COMPLETE')
`,
        )

        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        // Create VFS content with a known file
        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'safe-content')

        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        const injectResult = await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )
        expect(injectResult.code).toBe(0)

        const execResult = await spawn(seaBinary, [])

        expect(execResult.stdout).toContain('TRAVERSAL_TEST_COMPLETE')
        // All traversal leaks must be blocked
        expect(execResult.stdout).toContain('LEAKED=0')
        expect(execResult.stdout).not.toContain('LEAKED:')
        expect(execResult.stdout).not.toContain('EXISTS_LEAKED:')
        expect(execResult.stdout).not.toContain('UNEXPECTED_ERROR:')
        // Valid VFS file must still work
        expect(execResult.stdout).toContain('VFS_READ_OK=safe-content')
      })

      it('should block statSync traversal leaks', async () => {
        const testDir = path.join(testTmpDir, 'vfs-traversal-stat')
        await safeMkdir(testDir)

        const appJs = path.join(testDir, 'app.js')
        await fs.writeFile(
          appJs,
          `
const fs = require('fs')

const leakPaths = [
  '/snapshot/../etc/passwd',
  '/snapshot/../../etc',
  '/snapshot/../',
]

let blocked = 0
for (const attack of leakPaths) {
  try {
    fs.statSync(attack)
    console.log('STAT_LEAKED:' + attack)
  } catch (err) {
    if (err.code === 'ENOENT') {
      blocked++
    }
  }
}

// Also check lstatSync
for (const attack of leakPaths) {
  try {
    fs.lstatSync(attack)
    console.log('LSTAT_LEAKED:' + attack)
  } catch (err) {
    if (err.code === 'ENOENT') {
      blocked++
    }
  }
}

console.log('STAT_BLOCKED=' + blocked)
console.log('STAT_TEST_COMPLETE')
`,
        )

        const seaConfig = path.join(testDir, 'sea-config.json')
        await fs.writeFile(
          seaConfig,
          JSON.stringify({
            disableExperimentalSEAWarning: true,
            main: 'app.js',
            output: 'app.blob',
          }),
        )

        const vfsDir = path.join(testDir, 'vfs-content')
        await safeMkdir(vfsDir)
        await fs.writeFile(path.join(vfsDir, 'test.txt'), 'content')

        const vfsTar = path.join(testDir, 'vfs.tar')
        await spawn('tar', ['cf', vfsTar, '-C', vfsDir, '.'], {
          env: { ...process.env, COPYFILE_DISABLE: '1' },
        })

        const seaBinary = path.join(testDir, 'app')
        await fs.copyFile(finalBinaryPath, seaBinary)
        await makeExecutable(seaBinary)

        const injectResult = await runBinject(
          seaBinary,
          'BOTH',
          { sea: 'sea-config.json', vfs: vfsTar },
          {
            machoSegmentName: MACHO_SEGMENT_NODE_SEA,
            sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
            testDir,
          },
        )
        expect(injectResult.code).toBe(0)

        const execResult = await spawn(seaBinary, [])

        expect(execResult.stdout).toContain('STAT_TEST_COMPLETE')
        expect(execResult.stdout).not.toContain('STAT_LEAKED:')
        expect(execResult.stdout).not.toContain('LSTAT_LEAKED:')
      })
    })
  },
)
