#!/usr/bin/env node
/**
 * @file Generate docker/build.sh from build-step-defs.mts.
 *   Runs on the host (.mts), emits pure bash (.sh) that runs inside the
 *   btm-builder-glibc prebake (gcc-toolset-13, cmake, perl, go,
 *   ninja-build, libatomic — all in the shared prebake; see
 *   packages/build-infra/docker/btm-builder-glibc.Dockerfile). The
 *   container has Node + pnpm too but this build path doesn't use them.
 *   Output: docker/build.sh — tracked + committed so `docker build` sees
 *   it. The vitest in test/build-defs-drift.test.mts re-runs this emit
 *   step and asserts the result equals what's in docker/build.sh, so a
 *   forgotten regen fails CI.
 *   Per fleet rule "1 path, 1 reference" — build-step-defs.mts is the
 *   only place to edit build commands.
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

import { errorMessage } from 'build-infra/lib/error-utils'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'

import {
  BUILD_STEPS,
  EXTRA_YUM_PACKAGES,
  PUBLISH_ARTIFACTS,
  PUBLISH_HEADERS,
} from './build-step-defs.mts'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PACKAGE_ROOT = path.resolve(__dirname, '..')
const OUTPUT_PATH = path.join(PACKAGE_ROOT, 'docker', 'build.sh')
const logger = getDefaultLogger()

/**
 * Bash-quote a single arg. Wraps in single quotes; escapes embedded
 * single quotes by closing + escaping + reopening.
 * foo        → 'foo'
 * it's       → 'it'\''s'
 * $UPSTREAM  → '$UPSTREAM' — but we WANT this expanded by bash, so
 * the caller passes the placeholder unquoted.
 *
 * For our use, args fall into two categories:
 *
 * - Plain literals (e.g. -DBUILD_TESTING=OFF) → safe to single-quote.
 * - Placeholder references ($UPSTREAM_DIR, etc.) → emit unquoted so bash expands
 *   them.
 *
 * The caller's responsibility: pass unquoted strings for things that
 * should be bash-interpreted, quoted strings for everything else.
 */
function bashQuote(arg: string): string {
  // Placeholder pass-through: $VAR or $VAR/sub/path — emit verbatim,
  // bash will expand.
  if (/^\$[A-Z_][A-Z_0-9]*(\/[^\s]*)?$/.test(arg)) {
    return arg
  }
  // Already-safe args: no shell metachars + non-empty → no quoting.
  if (/^[A-Za-z0-9_./=:+-]+$/.test(arg) && arg.length > 0) {
    return arg
  }
  // Anything else: single-quote-escape.
  return `'${arg.replace(/'/g, `'\\''`)}'`
}

function emitBashFooter(): string {
  return `
echo "✓ boringssl-builder docker build complete"
`
}

function emitBashHeader(): string {
  return `#!/bin/bash
# DO NOT EDIT — generated by scripts/emit-docker-build.mts from
# scripts/build-step-defs.mts. Regenerate via:
#
#   pnpm --filter boringssl-builder run emit-docker-build
#
# Runs inside the manylinux2014 container — no Node, no pnpm.
# Inputs (env vars expected to be set by the Dockerfile):
#   UPSTREAM_DIR       — path to upstream/boringssl/ inside the container
#   CMAKE_BUILD_DIR    — scratch dir for cmake's intermediate output
#   OUT_LIB_DIR        — destination for libsmol_*.a artifacts
#   OUT_INCLUDE_DIR    — destination for the prefixed openssl/*.h tree

set -euo pipefail

: "\${UPSTREAM_DIR:?UPSTREAM_DIR not set}"
: "\${CMAKE_BUILD_DIR:?CMAKE_BUILD_DIR not set}"
: "\${OUT_LIB_DIR:?OUT_LIB_DIR not set}"
: "\${OUT_INCLUDE_DIR:?OUT_INCLUDE_DIR not set}"

mkdir -p "$CMAKE_BUILD_DIR" "$OUT_LIB_DIR" "$OUT_INCLUDE_DIR"
`
}

function emitBuildSteps(): string {
  const lines: string[] = []
  for (const step of BUILD_STEPS) {
    lines.push('')
    lines.push(`# ${step.label}`)
    const quoted = step.args.map(bashQuote).join(' ')
    lines.push(`echo "→ ${step.label}"`)
    lines.push(`${step.cmd} ${quoted}`)
  }
  return lines.join('\n')
}

function emitPublishArtifacts(): string {
  const lines: string[] = []
  lines.push('')
  lines.push('# Publish renamed static libs')
  for (const art of PUBLISH_ARTIFACTS) {
    lines.push(`if [ ! -f "${art.from}" ]; then`)
    lines.push(`  echo "× expected build artifact not found: ${art.from}" >&2`)
    lines.push(`  exit 1`)
    lines.push(`fi`)
    lines.push(`cp "${art.from}" "${art.to}"`)
    lines.push(`echo "  $(basename '${art.from}') → $(basename '${art.to}')"`)
  }
  return lines.join('\n')
}

function emitPublishHeaders(): string {
  const lines: string[] = []
  lines.push('')
  lines.push('# Publish include/ tree')
  const fromSubdir = PUBLISH_HEADERS.fromSubdir
  // toSubdir "." means copy CONTENTS into OUT_INCLUDE_DIR.
  const cpDest =
    PUBLISH_HEADERS.toSubdir === '.'
      ? '"$OUT_INCLUDE_DIR/"'
      : `"$OUT_INCLUDE_DIR/${PUBLISH_HEADERS.toSubdir}"`
  lines.push(`cp -R "$UPSTREAM_DIR/${fromSubdir}/." ${cpDest}`)
  lines.push(`echo "  include/ → $OUT_INCLUDE_DIR"`)
  return lines.join('\n')
}

/**
 * Produce the complete bash script as a single string. Returning a
 * string (rather than writing to disk) makes the drift-check test
 * trivial: compare the in-memory output to the on-disk file.
 */
export function emitDockerBuildScript(): string {
  return [
    emitBashHeader(),
    emitBuildSteps(),
    emitPublishArtifacts(),
    emitPublishHeaders(),
    emitBashFooter(),
  ].join('\n')
}

/**
 * Convenience export for consumers that want EXTRA_YUM_PACKAGES alongside
 * the script. Used by the Dockerfile-generation logic at the wheelhouse
 * layer if/when we lift this pattern.
 */
export function getExtraYumPackages(): readonly string[] {
  return EXTRA_YUM_PACKAGES
}

async function main(): Promise<void> {
  const content = emitDockerBuildScript()
  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true })
  await fs.writeFile(OUTPUT_PATH, content, 'utf8')
  await fs.chmod(OUTPUT_PATH, 0o755)
  logger.success(
    `Emitted ${path.relative(PACKAGE_ROOT, OUTPUT_PATH)} (${content.length} bytes)`,
  )
}

// Run main() only when executed directly (skip when imported by tests
// or by build.mts).
if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1]!)) {
  main().catch(err => {
    logger.fail(`emit failed: ${errorMessage(err)}`)
    process.exitCode = 1
  })
}
